// Seed data sourced from "LabNova_Website_Product_Category_Images.docx".
// Prices are indicative placeholders (no pricing was supplied) — edit them
// any time from Admin > Products once the app is running.

export const categories = [
  { name: "Plasticware", slug: "plasticware", sort_order: 1 },
  { name: "Glassware", slug: "glassware", sort_order: 2 },
  { name: "Laboratory Consumables", slug: "consumables", sort_order: 3 },
  { name: "Safety & PPE", slug: "safety-ppe", sort_order: 4 },
];

export const products = [
  {
    categorySlug: "plasticware",
    name: "Amber PET Container 370 mL (Square)",
    slug: "amber-pet-container-370ml",
    sku: "LN-PW-101",
    description: "Square amber PET container with a tamper-evident screw cap.",
    fullDescription:
      "A square-format amber PET container built to shield light-sensitive contents while standing securely on the bench. The wide neck and tamper-evident screw cap make filling, dispensing and everyday handling straightforward.",
    price: 9.9,
    image: "/assets/products/plasticware-container-370ml.png",
    sizes: [],
    specifications: [
      "Amber PET (UV-protective)",
      "Square body format",
      "Tamper-evident screw cap",
      "Capacity: 370 mL",
      "Dimensions: 11.7 × 6.7 × 5.7 cm (H×W×L)",
    ],
    features: [
      "Blocks UV light to protect sensitive contents",
      "Wide neck for easy filling and cleaning",
      "Stable square footprint for bench storage",
    ],
    applications: ["Bulk reagent storage", "Light-sensitive sample storage", "Dispensing and decanting"],
  },
  {
    categorySlug: "plasticware",
    name: "Amber PET Container 120 mL (Round)",
    slug: "amber-pet-container-120ml",
    sku: "LN-PW-102",
    description: "Compact round amber PET container for smaller-volume storage.",
    fullDescription:
      "A compact, round-format amber PET container suited to smaller-volume storage and dispensing tasks where bench space is at a premium. Finished with the same tamper-evident screw cap as the rest of the range.",
    price: 6.5,
    image: "/assets/products/plasticware-container-120ml.png",
    sizes: [],
    specifications: [
      "Amber PET (UV-protective)",
      "Round body format",
      "Tamper-evident screw cap",
      "Capacity: 120 mL",
      "Dimensions: 7.1 × 5.1 × 6.8 cm (H×W×L)",
    ],
    features: [
      "Compact round profile",
      "UV light protection",
      "Secure leak-resistant seal",
    ],
    applications: ["Sample storage", "Small-volume reagent storage", "Dispensing"],
  },
  {
    categorySlug: "plasticware",
    name: "50 mL Conical Centrifuge Tube",
    slug: "conical-centrifuge-tube-50ml",
    sku: "LN-PW-201",
    description: "Polypropylene conical tube with screw cap, graduated to 5 mL.",
    fullDescription:
      "A robust polypropylene conical centrifuge tube with a silicone-sealed screw cap and clear printed graduations, built for reliable sample centrifugation and bulk storage across everyday laboratory workflows.",
    price: 18.9,
    image: "/assets/products/plasticware-falcon-tube-50ml.png",
    sizes: [],
    specifications: [
      "Polypropylene conical tube",
      "Screw cap with silicone seal",
      "Capacity: 50 mL",
      "Graduated in 5 mL increments",
      "Pack size: 25 tubes",
    ],
    features: ["Leak-proof screw cap", "Printed graduation scale", "Sterile options available"],
    applications: ["Sample centrifugation", "Bulk sample storage", "General laboratory use"],
  },
  {
    categorySlug: "plasticware",
    name: "10 mL Conical Centrifuge Tube",
    slug: "conical-centrifuge-tube-10ml",
    sku: "LN-PW-202",
    description: "Polypropylene conical tube with screw cap, graduated to 1 mL.",
    fullDescription:
      "A smaller-format conical centrifuge tube offering the same silicone-sealed screw cap and clear graduation scale as its 50 mL counterpart, sized for lower-volume centrifugation and storage needs.",
    price: 14.5,
    image: "/assets/products/plasticware-falcon-tube-10ml.png",
    sizes: [],
    specifications: [
      "Polypropylene conical tube",
      "Screw cap with silicone seal",
      "Capacity: 10 mL",
      "Graduated in 1 mL increments",
      "Pack size: 25 tubes",
    ],
    features: ["Leak-proof screw cap", "Printed graduation scale", "Sterile options available"],
    applications: ["Sample centrifugation", "Small-volume sample storage", "General laboratory use"],
  },
  {
    categorySlug: "glassware",
    name: "250 mL Amber Glass Beaker",
    slug: "amber-glass-beaker-250ml",
    sku: "LN-GW-301",
    description: "Low-form amber borosilicate beaker with a moulded pour spout.",
    fullDescription:
      "A low-form amber borosilicate beaker combining thermal shock resistance with UV protection for light-sensitive solutions. The moulded pour spout and clear printed scale keep everyday mixing and measuring dependable.",
    price: 15.9,
    image: "/assets/products/glassware-beaker-250ml.png",
    sizes: [],
    specifications: [
      "Amber borosilicate glass",
      "Low-form graduated beaker",
      "Capacity: 250 mL (approx. graduations)",
      "Moulded pour spout",
    ],
    features: [
      "UV protection for light-sensitive solutions",
      "Thermal shock resistant",
      "Clear printed scale",
    ],
    applications: ["Solution preparation", "Heating and mixing", "Light-sensitive formulations"],
  },
  {
    categorySlug: "glassware",
    name: "100 mL Amber Volumetric Flask",
    slug: "amber-volumetric-flask-100ml",
    sku: "LN-GW-302",
    description: "Single-mark amber volumetric flask with a ground-glass stopper.",
    fullDescription:
      "A precision single-mark amber volumetric flask, calibrated to ±0.1 mL at 20°C and supplied with an interchangeable ground-glass stopper — built for accurate, repeatable solution preparation away from direct light.",
    price: 24.9,
    image: "/assets/products/glassware-volumetric-flask-100ml.png",
    sizes: [],
    specifications: [
      "Amber borosilicate glass",
      "Single graduation mark",
      "Capacity: 100 mL ± 0.1 mL at 20°C",
      "Supplied with glass stopper",
    ],
    features: [
      "High-precision single-mark calibration",
      "UV light protection",
      "Interchangeable ground-glass stopper",
    ],
    applications: ["Precise solution preparation", "Standard and reagent preparation", "Light-sensitive analytical work"],
  },
  {
    categorySlug: "glassware",
    name: "2 mL HPLC Vial (Clear Glass)",
    slug: "hplc-vial-clear-2ml",
    sku: "LN-GW-401",
    description: "Clear glass HPLC vial with screw neck and graduated fill markings.",
    fullDescription:
      "A clear glass HPLC vial with a screw neck and graduated 0.5 / 1.0 / 1.5 mL fill markings, chemically inert and dimensioned for consistent seating in standard autosamplers.",
    price: 32.0,
    image: "/assets/products/glassware-hplc-vial-clear-2ml.png",
    sizes: [],
    specifications: [
      "Clear glass",
      "Screw neck",
      "Graduated at 0.5 / 1.0 / 1.5 mL",
      "Pack size: 100 vials",
    ],
    features: [
      "Chemically inert clear glass",
      "Graduated fill markings",
      "Consistent thread for secure sealing",
    ],
    applications: ["HPLC / GC sample analysis", "Autosampler use", "Small-volume sample storage"],
  },
  {
    categorySlug: "glassware",
    name: "2 mL HPLC Vial (Amber Glass)",
    slug: "hplc-vial-amber-2ml",
    sku: "LN-GW-402",
    description: "Amber glass HPLC vial for light-sensitive analytical samples.",
    fullDescription:
      "An amber glass HPLC vial offering the same screw neck and graduated fill markings as the clear version, with added UV protection for light-sensitive analytical samples.",
    price: 34.0,
    image: "/assets/products/glassware-hplc-vial-amber-2ml.png",
    sizes: [],
    specifications: [
      "Amber glass",
      "Screw neck",
      "Graduated at 0.5 / 1.0 / 1.5 mL",
      "Pack size: 100 vials",
    ],
    features: [
      "UV protection for light-sensitive samples",
      "Graduated fill markings",
      "Consistent thread for secure sealing",
    ],
    applications: ["HPLC / GC sample analysis", "Autosampler use", "Light-sensitive sample storage"],
  },
  {
    categorySlug: "consumables",
    name: "1 mL Pipette Tips",
    slug: "pipette-tips-1ml",
    sku: "LN-LC-501",
    description: "Universal-fit polypropylene pipette tips, pack of 500.",
    fullDescription:
      "Universal-fit polypropylene pipette tips engineered for a consistent tip aperture and low sample retention, supporting dependable liquid handling across routine and molecular biology workflows.",
    price: 12.5,
    image: "/assets/products/consumables-pipette-tips-1ml.png",
    sizes: [],
    specifications: [
      "Universal fit",
      "Polypropylene construction",
      "Capacity: up to 1 mL",
      "Sterile option available",
      "Pack size: 500 tips",
    ],
    features: ["Universal pipette compatibility", "Consistent tip aperture", "Low-retention surface"],
    applications: ["Liquid handling", "Molecular biology", "Routine pipetting"],
  },
  {
    categorySlug: "consumables",
    name: "5 mL Pipette Tips",
    slug: "pipette-tips-5ml",
    sku: "LN-LC-502",
    description: "Universal-fit polypropylene pipette tips, pack of 120.",
    fullDescription:
      "A larger-capacity universal-fit pipette tip built to the same tolerances as the 1 mL tips, suited to higher-volume transfers without sacrificing accuracy.",
    price: 16.9,
    image: "/assets/products/consumables-pipette-tips-5ml.png",
    sizes: [],
    specifications: [
      "Universal fit",
      "Polypropylene construction",
      "Capacity: up to 5 mL",
      "Sterile option available",
      "Pack size: 120 tips",
    ],
    features: ["Universal pipette compatibility", "Consistent tip aperture", "Low-retention surface"],
    applications: ["Liquid handling", "Reagent transfer", "Routine pipetting"],
  },
  {
    categorySlug: "consumables",
    name: "Nitrile Examination Gloves",
    slug: "nitrile-examination-gloves",
    sku: "LN-LC-601",
    description: "Powder-free, latex-free nitrile gloves with textured fingertips.",
    fullDescription:
      "Powder-free, latex-free nitrile examination gloves with textured fingertips and a beaded cuff, offering dependable single-use protection for general laboratory handling.",
    price: 11.9,
    image: "/assets/products/consumables-nitrile-gloves.png",
    sizes: ["Small", "Medium", "Large", "X-Large"],
    specifications: [
      "Powder-free nitrile",
      "Non-sterile, ambidextrous",
      "Textured fingertips",
      "Beaded cuff",
      "Latex free",
      "Pack size: 100 gloves",
    ],
    features: ["Latex-free for reduced allergy risk", "Textured grip", "Single-use design"],
    applications: ["General lab handling", "Sample handling", "Cleaning and decontamination"],
  },
  {
    categorySlug: "consumables",
    name: "Laboratory Tissues",
    slug: "laboratory-tissues",
    sku: "LN-LC-602",
    description: "Soft, low-lint, high-absorbency 2-ply laboratory tissues.",
    fullDescription:
      "Soft, low-lint 2-ply laboratory tissues offering high absorbency for general bench clean-up, spill absorption and wiping down precision or optical surfaces without scratching.",
    price: 5.4,
    image: "/assets/products/consumables-lab-tissues.png",
    sizes: [],
    specifications: ["2-ply construction", "Soft, low-lint, high absorbency", "Pack size: 100 tissues"],
    features: ["Low-lint for optical and precision surfaces", "High absorbency", "Soft, non-abrasive"],
    applications: ["Wiping optical equipment", "General bench clean-up", "Spill absorption"],
  },
  {
    categorySlug: "safety-ppe",
    name: "Laboratory Coat",
    slug: "laboratory-coat",
    sku: "LN-SP-701",
    description: "Long-sleeve, button-front laboratory coat with pockets, S–3XL.",
    fullDescription:
      "A long-sleeve, button-front laboratory coat in a comfortable poly-cotton blend, finished with a chest pocket and two front pockets for practical everyday storage across teaching and laboratory environments.",
    price: 42.0,
    image: "/assets/products/safety-lab-coat.png",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    specifications: [
      "Poly-cotton blend",
      "Long sleeve, button-front",
      "Chest pocket plus two front pockets",
      "Sizes: S – 3XL",
    ],
    features: ["Comfortable long-sleeve protection", "Secure button closure", "Practical pocket storage"],
    applications: ["General laboratory wear", "Teaching and training environments", "Light chemical splash protection"],
  },
  {
    categorySlug: "safety-ppe",
    name: "Safety Glasses",
    slug: "safety-glasses",
    sku: "LN-SP-702",
    description: "Wraparound safety glasses with an anti-scratch, UV-protective lens.",
    fullDescription:
      "Lightweight wraparound safety glasses with a clear polycarbonate, anti-scratch, UV-protective lens — comfortable enough for extended wear across general laboratory and teaching environments.",
    price: 8.9,
    image: "/assets/products/safety-glasses.png",
    sizes: [],
    specifications: [
      "Clear polycarbonate lens",
      "Wraparound design",
      "Anti-scratch coating",
      "UV protection",
    ],
    features: ["Wraparound coverage", "Anti-scratch lens coating", "Lightweight, comfortable fit"],
    applications: ["Eye protection during lab work", "Chemical splash protection", "Teaching laboratories"],
  },
];
